repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
              docs/src/diagrams/export/|
          )|
          .drawio$
      - id: trailing-whitespace
        exclude: |
          (?x)^(
              docs/src/diagrams/export/|
          )|
          .drawio$
      - id: check-json
  - repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
      - id: black
        files: ^(src/|tests/)
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        files: ^(src/|tests/)
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        files: ^(src/|tests/)
        args: [ "--profile", "black" ]
