repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: ^(docs/src/diagrams/export/)
      - id: trailing-whitespace
        exclude: ^(docs/src/diagrams/export/)
      - id: check-json
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        files: ^(src/|test/)
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        files: ^(src/|test/)
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        files: ^(src/|test/)
        args: [ "--profile", "black" ]
