repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    - id: debug-statements
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-json
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      files: ^(src/|test/)
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
    - id: flake8
      files: ^(src/|test/)
