FROM nexus.engageska-portugal.pt/ska-telescope/oet:latest

USER root

RUN sudo apt-get update && sudo apt-get install -y openssh-server

RUN mkdir /var/run/sshd
RUN echo 'tango:oet' | chpasswd

RUN echo "PermitUserEnvironment yes" >> /etc/ssh/sshd_config

RUN echo "cd /app" >> /home/tango/.bashrc
RUN echo "/venv/bin/itango3 --profile=ska" >> /home/tango/.bashrc
# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]