@startuml
'https://plantuml.com/sequence-diagram

autonumber

ScriptExecutionService -> ProcessManager: create
alt commit hash not given
    ProcessManager -> ProcessManager: calculate hash
end

ProcessManager -> EnvironmentManager: environment_for(hash)
alt not environment for hash
    EnvironmentManager -> EnvironmentManager: create Environment(creating_condition, created_condition)
    EnvironmentManager -> EnvironmentManager: map hash to Environment
end
EnvironmentManager --> ProcessManager: return Environment

create ScriptWorker
ProcessManager -> ScriptWorker: init(Environment, script_args)

ScriptWorker --> ProcessManager: STATE=CREATING
alt Environment.creating_condition not set
    ScriptWorker -> ScriptWorker: set Environment.creating_condition
    ScriptWorker -> ScriptWorker: clone project
    ScriptWorker -> ScriptWorker: install project
    ScriptWorker -> ScriptWorker: set Environment.created_condition
end
ScriptWorker -> ScriptWorker: wait_for(Environment.created_condition)

ScriptWorker -> ScriptWorker: load user script module
ScriptWorker -> ScriptWorker: call load user script init

ScriptWorker --> ProcessManager: STATE=CREATED

@enduml
