@startuml
'https://plantuml.com/class-diagram

package ska_oso_oet {

    package mptools {
        note as mptools_note
        See the ScriptExecutionService
        view for more information on
        the ""mptools"" module and its
        contents.
        end note
    }

    package main <<Rectangle>> {
        class ScriptExecutionServiceWorker {
            prepare(...)
            start(...)
            stop(...)
            list(...)
        }

        class ActivityWorker {
            run(...)
            list(...)
        }

        class FastAPIWorker {
        }

        class EventBusWorker {
            republish(...)
        }

        class main_func <<function>>

        ScriptExecutionServiceWorker -up-|> EventBusWorker
        FastAPIWorker -up-|> EventBusWorker
        ActivityWorker -up-|> EventBusWorker
    }

    package ui <<Rectangle>> {
        class create_app <<function>>
        class ServerSentEventsBlueprint

        note as app_note
        create_app function will
        create a FastAPI application
        using ProcedureAPI, ActivityAPI
        and SSE API routers.
        end note

        app_note -left- create_app
    }

    FastAPIWorker *-- create_app

    package procedure {

        package ui as procedure_ui <<Rectangle>> {
            class ProcedureAPI
        }

        package application as procedure_application <<Rectangle>> {
            class ScriptExecutionService
        }

        package domain as procedure_domain <<Rectangle>> {
        }
        ScriptExecutionServiceWorker --> ScriptExecutionService

    }

    package activity {
        package ui as activity_ui <<Rectangle>> {
            class ActivityAPI
        }

        package application as activity_application <<Rectangle>> {
            class ActivityService
        }

        package domain as activity_domain <<Rectangle>> {
        }
        ActivityWorker --> ActivityService
    }
}

EventBusWorker -[dotted]- mptools: uses

procedure_application -down[hidden]- procedure_ui
activity_application -down[hidden]- activity_ui
create_app -down[hidden]- ServerSentEventsBlueprint

@enduml
