@startuml
'https://plantuml.com/class-diagram

package ska_oso_oet {

    package main <<Rectangle>> {

        class ActivityWorker {
            run(...)
        }

        class FastAPIWorker

        class EventBusWorker {
            main_loop(...)
            main_func(...)
            republish(...)
        }

        ActivityWorker -up-|> EventBusWorker
        FastAPIWorker -up-|> EventBusWorker
    }

    package ui <<Rectangle>> {

        class app <<function return value>> {
        }
    }

    package activity {

        package ui as activity_ui <<Rectangle>> {
            class ActivityAPI
        }
        app o-- ActivityAPI


        package application <<Rectangle>> {

            class ActivityCommand {
                sbd_id: str
                activity_name: str
                prepare_only: bool
                arg_override: Dict
            }

            class ActivityService {
                history: List[ActivitySummary]
                run(cmd: ActivityCommand) -> ActivitySummary
            }

            class ActivitySummary {
                activity_id: int
                procedure_id: int
                sbd_id: str
                activity_name: str
                prepare_only: bool
                arg_override: List[ArgCapture]
                activity_states: List[(ActivityState, timestamp)]
            }

        }

        package domain as activity_domain <<Rectangle>> {
            enum ActivityState {
                REQUESTED
            }
        }

        FastAPIWorker *-- app
        ActivityWorker *-- ActivityService
    }

    package procedure {

        package domain as procedure_domain <<Rectangle>> {
            class ArgCapture {
                fn: str
                fn_args: domain.ProcedureInput
                time: float
            }
        }
        ActivitySummary -left-|> ArgCapture

    }
}

activity_ui -down[hidden]- application
application -down[hidden]- activity_domain

'main -down[hidden]--> application
'restserver -left[hidden]--> application
'FastAPIWorker -down[hidden]--> restserver
ActivitySummary -right[hidden]- ActivityCommand
ActivityService -down[hidden]- ActivitySummary

@enduml
