@startuml
'https://plantuml.com/sequence-diagram


mainframe **Activity API over REST**

autonumber

participant cli as "CLI :\nRestClientUI" #lightgreen
participant FlaskWorker as "REST backend :\nFlaskWorker" #lightblue
participant ActivityWorker
participant ActivityService
participant ODA as "ODA :\nObservation Data Archive" #lightblue
participant ScriptExecutionServiceWorker as "SESWorker :\nScriptExecutionServiceWorker"
participant ScriptExecutionService as "Script Execution API :\nScriptExecutionService"

cli -> FlaskWorker: HTTP POST to /api/v1/activities

FlaskWorker -> ActivityWorker: send message request.activity.run

ActivityWorker -> ActivityService: run(cmd: ActivityCommand)

ActivityService -> ODA: get_sbd(sbd_id)
ODA -> ActivityService: pdm.SchedulingBlock
opt arg_override provided
ActivityService -> ActivityService: update SB args
end

ActivityService -> ScriptExecutionServiceWorker: message request.procedure.prepare

ScriptExecutionServiceWorker -> ScriptExecutionService: prepare(cmd: PrepareProcessCommand)

ScriptExecutionService -> ScriptExecutionServiceWorker: ProcedureSummary

ScriptExecutionServiceWorker -> ActivityService: message procedure.lifecycle.preparing

ActivityService -> ActivityWorker: ActivitySummary

ActivityWorker -> FlaskWorker: message activity.lifecycle.running

cli <- FlaskWorker: HTTP OK + ActivitySummary JSON

opt prepare_only not set
ActivityService -> ScriptExecutionServiceWorker: message request.procedure.start (force=true)

ScriptExecutionServiceWorker -> ScriptExecutionService: start(cmd: StartProcessCommand)

ScriptExecutionService -> ScriptExecutionServiceWorker: ProcedureSummary

ScriptExecutionServiceWorker -> ActivityService: message procedure.lifecycle.started

ActivityService -> ActivityWorker: ActivitySummary

end

@enduml
