@startuml
'https://plantuml.com/class-diagram

package ska_oso_oet_client {
    package restclient <<Rectangle>> {
        class RestClientUI {
            create(...)
            start(...)
            stop(...)
            list(...)
            describe(...)
            listen(...)
        }
    }
}

package ska_oso_oet {

    package mptools <<Rectangle>> {
        note as mptools_note
        See the ScriptExecutionService
        view for more information on
        the ""mptools"" module and its
        contents.
        end note
    }

    package main <<Rectangle>> {
        class ScriptExecutionServiceWorker {
            prepare(...)
            start(...)
            stop(...)
            list(...)
        }

        class FastAPIWorker

        class EventBusWorker {
            main_loop(...)
            main_func(...)
            republish(...)
        }

        ScriptExecutionServiceWorker -up-|> EventBusWorker
        FastAPIWorker -up-|> EventBusWorker
        EventBusWorker -right[dotted]- mptools: uses
        EventBusWorker -right[dotted]- pypubsub: uses
    }

    package ui <<Rectangle>> {
        class app <<function return value>> {
        }

        class ServerSentEventsBlueprint

        app o-- ServerSentEventsBlueprint
    }

    package procedure {

        package ui as procedure_ui <<Rectangle>> {
            class ProcedureAPI
        }
        app o-- ProcedureAPI

        package application <<Rectangle>> {

            note as N1
            See the Script Execution module
            view for information on objects
            from the ""domain"" Python module
            that are held as class properties
            of some of the classes in the
            ""application"" package.
            end note

            class ScriptExecutionService {
                prepare(cmd: PrepareProcessCommand) -> ProcedureSummary
                start(cmd: StartProcessCommand) -> ProcedureSummary
                stop(cmd: StopProcessCommand) -> List[ProcedureSummary]
                summarise(pids: List[int]) -> List[[ProcedureSummary]
            }

            class ProcedureSummary {
                id: int
                script: domain.ExecutableScript
                script_args: ...
                state: domain.ProcedureState
            }

            class ProcedureHistory {
                {field} process_states: List[(ProcedureState, time)]
                stacktrace: Optional[str]
            }
            ProcedureSummary --> ProcedureHistory

            together {
            class PrepareProcessCommand {
                script: domain.ExecutableScript
                init_args: domain.ProcedureInput
            }

            class StartProcessCommand {
                process_uid: int
                fn_name: str
                run_args: domain.ProcedureInput
            }

            class StopProcessCommand {
                process_uid: int
                run_abort: bool
            }
            }
            PrepareProcessCommand -[hidden]- StartProcessCommand
            StartProcessCommand -[hidden]- StopProcessCommand
        }
        FastAPIWorker *-- app
        ScriptExecutionServiceWorker --> ScriptExecutionService
    }

}


package pypubsub {
}

'main -down[hidden]--> application
'restserver -left[hidden]--> application
'FastAPIWorker -down[hidden]--> restserver
ScriptExecutionService -down[hidden]- ProcedureSummary
ScriptExecutionService -down[hidden]- PrepareProcessCommand
PrepareProcessCommand -right[hidden]- ProcedureSummary

@enduml
