apiVersion: v2
name: ska-oso-oet
description: A Helm chart for deploying the Observation Execution Tool on Kubernetes
type: application
version: 7.0.0
appVersion: 7.0.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
