# Default values for oet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
minikube: true

system: TM-mid
telescope: SKA-low
subsystem: ska-oso-oet
central_node: ska_low/tm_central/central_node
subarray: ska_low/tm_subarray_node

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000
  cluster_domain: techops.internal.skao.int

rest:
  enabled: true
  component: rest
  function: script-execution
  domain: operations
  logLevel: INFO
  ingress:
    enabled: false
  image:
    registry: artefact.skao.int
    image: ska-oso-oet
    tag: ~ # Defaults to the chart appVersion if not set
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu:  200m
      memory: 256Mi
    limits:
      cpu:  2000m
      memory: 1024Mi
  livenessProbe:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  oda:
    backendType: postgres
    postgres: # The below values are used to set environment variables that are used in the ODA Repository. If they are not set then the defaults defined by the ODA will be used.
      host: ~
      port: ~
      user: ~
      password: secretpassword # TODO BTN-2449 will extract this
      db:
        name: ~
  skuid:
    url:
  semantic_validation: true

# Configure Ingress
ingress:
  enabled: true
  nginx: true
  hostname: k8s.stfc.skao.int

nodeSelector: {}

affinity: {}

tolerations: []
