# Default values for oet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
minikube: true

system: TM-mid
telescope: SKA-mid
subsystem: ska-oso-oet

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000

rest:
  enabled: true
  component: rest
  function: script-execution
  domain: operations
  ingress:
    enabled: false
  image:
    registry: artefact.skao.int
    image: ska-oso-oet
    tag: 2.13.2
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu:  100m
      memory: 128Mi
    limits:
      cpu:  1000m
      memory: 128Mi
  livenessProbe:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

# Configure Ingress
ingress:
  enabled: true
  nginx: true
  hostname: k8s.stfc.skao.int

nodeSelector: {}

affinity: {}

tolerations: []
