# Default values for oet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
minikube: true

system: TM-mid
telescope: SKA-mid
subsystem: ska-oso-oet
central_node: ska_mid/tm_central/central_node
subarray: ska_mid/tm_subarray_node

# Location within the running OET application that static observing scripts
# (including abort.py script used directly by OET) are stored. Set in the
# Makefile as this value is required both at image build time as well as within
# the OET runtime environment.
scripts_location: ~

osd_validation_strictness: 2 # Set to 1 to disable OSD semantic validation

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000
  cluster_domain: techops.internal.skao.int

rest:
  enabled: true
  component: rest
  function: script-execution
  domain: operations
  logLevel: INFO
  ingress:
    enabled: false
  image:
    registry: artefact.skao.int
    image: ska-oso-oet
    tag: ~ # Defaults to the chart appVersion if not set
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu:  200m
      memory: 256Mi
    limits:
      cpu:  2000m
      memory: 1024Mi
  livenessProbe:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  oda:
    backendType: postgres
    url: ~ # The default service address of the ODA deployed in the same namespace is used if this is not set.
    majorVersion: 7 # Used in the default URL if the above value is not set. Should match the ODA chart version in the ska-oso-oet-umbrella chart.
    postgres:
      # The below values are used to set environment variables that are used in the ODA Repository.
      # If they are not set then the defaults defined by the ODA will be used.
      host: ~
      port: ~
      user: ~
      db:
        name: ~
      password:
        # This is the resource name of a k8s secret and the key the password is stored under.
        # If left as null the default secret deployed by the ODA umbrella will be used.
        secret: ~
        key: ~
  skuid:
    url: # Standard SKUID svc address is used if this is not set.


nodeSelector: {}

affinity: {}

tolerations: []
