# Default values for oet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
minikube: true

system: TM-mid
telescope: SKA-mid
subsystem: ska-oso-oet
central_node: ska_mid/tm_central/central_node
subarray: ska_mid/tm_subarray_node

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000

rest:
  enabled: true
  component: rest
  function: script-execution
  domain: operations
  logLevel: INFO
  ingress:
    enabled: false
  image:
    registry: artefact.skao.int
    image: ska-oso-oet
    tag: 4.0.7
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu:  200m
      memory: 256Mi
    limits:
      cpu:  2000m
      memory: 1024Mi
  livenessProbe:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  oda:
    backend:
      type: rest
    # For the ODA deployed by the umbrella chart, the url is only known at deploy time so is set in the Makefile
    # In the production system, the url should be static so can be set here.
    url:

# Configure Ingress
ingress:
  enabled: true
  nginx: true
  hostname: k8s.stfc.skao.int

nodeSelector: {}

affinity: {}

tolerations: []
