# Default values for oet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
minikube: true

system: TM-mid
telescope: SKA-mid
subsystem: observation-execution-tool

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000

ssh:
  enabled: true
  nodePort:
  component: ssh-console
  function: maintenance-interface
  domain: operations
  image:
    registry: nexus.engageska-portugal.pt/ska-telescope
    image: observation-execution-tool-ssh
    tag: 2.4.2
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 128Mi
  livenessProbe:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

itango:
  enabled: true
  nodePort:
  component: itango-console
  function: interactive-script-execution
  domain: operations
  image:
    registry: nexus.engageska-portugal.pt/ska-telescope
    image: observation-execution-tool-ssh
    tag: 2.4.2
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 128Mi
  livenessProbe:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

rest:
  enabled: true
  component: rest
  function: script-execution
  domain: operations
  image:
    registry: nexus.engageska-portugal.pt/ska-telescope
    image: observation-execution-tool
    tag: 2.4.2
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu:  100m
      memory: 128Mi
    limits:
      cpu:  1000m
      memory: 128Mi
  livenessProbe:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

jupyter:
  enabled: true
  component: jupyter
  function: interactive-script-execution
  domain: operations
  nodePort:
  storage:
    enabled: false
    hostPath: /home/ubuntu/skampi-hostpath/build/jupyter/
    capacity: 0.1G
    reclaimPolicy: Delete
  image:
    registry: nexus.engageska-portugal.pt/ska-telescope
    image: observation-execution-tool-jupyter
    tag: 2.4.2
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 128Mi
  livenessProbe:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

# Configure Ingress
ingress:
  enabled: true
  nginx: false
  hostname: integration.engageska-portugal.pt

  # Ingress annotations
  annotations: {}

  # Ingress TLS configuration
  #
  tls:
    enabled: true
    secretname: 'tls-secret-{{ template "oet.name" . }}-{{ .Release.Name }}'
    hostname: "{{ .Values.ingress.hostname }}"

nodeSelector: {}

affinity: {}

tolerations: []
