apiVersion: v2
name: ska-oso-oet-umbrella
description: Helm umbrella chart for the OET
type: application
version: 0.1.0
appVersion: 2.11.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
- name: ska-tango-base
  version: 0.2.23
  repository: https://artefact.skao.int/repository/helm-internal
- name: skuid
  version: 0.1.0
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: ska-oso-oet
  version: 0.2.0
  repository: file://../oet
