apiVersion: v2
name: ska-oso-oet-umbrella
description: Helm umbrella chart for the OET
type: application
version: 6.2.0
appVersion: 6.2.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
- name: ska-ser-skuid
  version: 3.3.3
  repository: https://artefact.skao.int/repository/helm-internal
- name: ska-oso-oet
  version: 6.2.0
  repository: file://../ska-oso-oet
- name: ska-db-oda
  version: 5.0.1
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-db-oda.enabled
