apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ska-oso-oet.name" . }}-{{ .Values.rest.component }}-{{ .Release.Name }}-environment
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-oso-oet.labels" . | indent 4 }}
    component:  {{ template "ska-oso-oet.name" . }}
    domain: environment
    function: ska-oso-oet-environment
    intent: production
data:
  LOG_LEVEL: {{ .Values.rest.logLevel }}
  KUBE_NAMESPACE: {{ .Release.Namespace }}
  TANGO_HOST: {{ if .Values.global.tango_host -}} {{ .Values.global.tango_host }} {{- else -}} databaseds-tango-base-{{ .Release.Name }}:10000 {{- end }}
  # This env variable is used by the OET CLI which is also included in the application. It is not required by the server itself
  OET_URL: http://{{ template "ska-oso-oet.name" . }}-rest-{{ .Release.Name }}:5000/{{ .Release.Namespace }}/oet/api/v{{ template "ska-oso-oet.major-version" . }}
  {{ if .Values.rest.skuid.url }}
  SKUID_URL: {{ .Values.rest.skuid.url }}
  {{ else }}
  SKUID_URL: ska-ser-skuid-{{ .Release.Name }}-svc.{{ .Release.Namespace }}.svc.{{ .Values.global.cluster_domain }}:9870
  {{ end }}
  SUBARRAYNODE_FQDN_PREFIX: {{.Values.subarray}}
  CENTRALNODE_FQDN: {{.Values.central_node}}
  SKA_TELESCOPE: {{.Values.telescope}}
  ODA_BACKEND_TYPE: {{ .Values.rest.oda.backendType }}
  POSTGRES_HOST: {{ if .Values.rest.oda.postgres.host }} {{ .Values.rest.oda.postgres.host }} {{ else }} {{ .Release.Name }}-postgresql {{ end }}
  ADMIN_POSTGRES_PASSWORD: {{ .Values.rest.oda.postgres.password }}
  {{ if .Values.rest.oda.postgres.port }}
  POSTGRES_PORT: {{ .Values.rest.oda.postgres.port | quote }}
  {{ end }}
  {{ if .Values.rest.oda.postgres.db.name }}
  POSTGRES_DB_NAME: {{ .Values.rest.oda.postgres.db.name }}
  {{ end }}
  {{ if .Values.rest.oda.postgres.user }}
  ADMIN_POSTGRES_USER: {{ .Values.rest.oda.postgres.user }}
  {{ end }}
