apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ska-oso-oet.name" . }}-{{ .Values.rest.component }}-{{ .Release.Name }}-environment
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-oso-oet.labels" . | indent 4 }}
    component:  {{ template "ska-oso-oet.name" . }}
    domain: environment
    function: ska-oso-oet-environment
    intent: production
data:
  TANGO_HOST: {{ if .Values.global.tango_host -}} {{ .Values.global.tango_host }} {{- else -}} databaseds-tango-base-{{ .Release.Name }}:10000 {{- end }}
  OET_READ_VIA_PUBSUB: {{ .Values.rest.featureFlags.readViaPubSub | default "true" | quote }}
  OET_REST_URI: http://{{ template "ska-oso-oet.name" . }}-rest-{{ .Release.Name }}:5000/api/v1.0/procedures
  SKUID_URL: "ska-ser-skuid-{{ .Release.Name }}-svc.{{ .Release.Namespace }}.svc.cluster.local:9870"
  SUBARRAYNODE_FQDN_PREFIX: {{.Values.subarray}}
  CENTRALNODE_FQDN: {{.Values.central_node}}
  SKA_TELESCOPE: {{.Values.telescope}}